// LineFollowerOS Example Sketch for Arduino
// Generated by LineFollowerOS - Customize via web interface

#include "LineFollower.h"

// Configuration - EDIT THESE VALUES
#define NUM_SENSORS 8
int sensorPins[NUM_SENSORS] = {A0, A1, A2, A3, A4, A5, A6, A7};

#define MOTOR_LEFT_PIN1 9
#define MOTOR_LEFT_PIN2 10
#define MOTOR_RIGHT_PIN1 5
#define MOTOR_RIGHT_PIN2 6

// Create LineFollower instance
LineFollower robot(NUM_SENSORS, sensorPins, 
                   MOTOR_LEFT_PIN1, MOTOR_LEFT_PIN2,
                   MOTOR_RIGHT_PIN1, MOTOR_RIGHT_PIN2);

void setup() {
    robot.begin();
    robot.setPID(1.0, 0.0, 0.5);  // Kp, Ki, Kd
    robot.setSpeed(150, 200);     // baseSpeed, maxSpeed
    
    // Calibration delay
    delay(2000);
    Serial.println("Starting in 3...");
    delay(1000);
    Serial.println("2...");
    delay(1000);
    Serial.println("1...");
    delay(1000);
    Serial.println("GO!");
}

void loop() {
    robot.run();
    delay(10);  // Small delay for stability
}
